#coding=utf8

__author__ = 'WangHai zhen'

import base64
print(base64.b64encode(b'XDRjXDY5XDY2XDY1XDIwXDY5XDczXDIwXDczXDY4XDZmXDcyXDc0XDJjXDIwXDQ5XDIwXDc1XDczXDY1XDIwXDcwXDc5XDc0XDY4XDZmXDZlXDJlXGFcNGNcNjlcNjZcNjVcMjBcNjlcNzNcMjBcNjJcNjVcNjFcNzVcNzRcNjlcNjZcNzVcNmNcMmNcMjBcNDlcMjBcNmNcNmZcNzZcNjVcMjBcNjJcNjFcNmZcNjJcNjFcNmZcMmU='))